
let songs = [ { Id: 0,
    
        name: "Ande ka fanda",
        movie: "Jodi No. 1 " ,
        path: "https://od.lk/s/NDRfMjkzMzMzODVf/02.%20Andde%20Ka%20Funda%20%281%29.mp3"
       
        
    },
  { Id: 1,
    name: "Jaane Kyon",
        movie: "Dil Chahta Hai",
        path: "https://od.lk/s/NDRfMjkzMzMzMDlf/Jaane%20Kyon%20Log%20Pyar.mp3"
    },
  
  { Id: 2,
    name: "Bade Miyan",
    movie: "Bade Miyan Chote Miyan",
    path: "https://od.lk/s/NDRfMjkzMzMzMjVf/01%20Bade%20Miyan%20Chote%20Miyan%20-%20www.downloadming.com.mp3",
},
  { Id: 3,
    name: "Pyar Ka Dushman",
    movie: "Amar Akbar Anthony",
    path: "https://od.lk/s/NDRfMjkzMzMzNDJf/Taiyabali%20Pyar%20Ka%20Dushman.mp3",
},
  { Id: 4,
    name: "Main Jaadugar",
        movie: "Jaadugar",
        path: "https://od.lk/s/NDRfMjkzMzMzNTlf/Main%20Jaadugar%203.mp3",
    },
  { Id: 5,
    name: "Paanch Rupaiya Baara Aana",
    movie: "Chalti Ka Naam Gaadi",
    path: "https://od.lk/s/ff3b69184a30d365fc71e4a4456c1e826ee6e1905e4bcbb42578d007c70a5a70/Main-Sitaron-Ka-Tarana-%28pagalworldsongs.co.in%29%20%282%29.mp3",
},
  { Id: 6,
    name: "Churalo Na Dil Mera",
    movie: "Kareeb",
 
    path: "https://od.lk/s/NDRfMjkzMzMzNjVf/128-Churalo%20Na%20Dil%20Mera%20-%20Kareeb%20128%20Kbps.mp3",
},
  { Id: 7,
    name: "Bombay Se Aaya Mera Dost",
    movie: "Aap Ki Khatir",
    path: "https://od.lk/s/NDRfMjkzMzE5NzFf/Bambai-Se-Aaya-Mera-Dost-Bappi-Lahiri-%28pagalworldsongs.co.in%29.mp3",
},
  { Id: 8,
    name: "Padosan Apni Murgi",
        movie: "Jaadugar",
        path: " https://od.lk/s/NDRfMjkzMzMzNzFf/Padosan_Apni_Murgi_Ko_Rakhna_5.mp3",
    },
    { Id: 9,
        name: "Coolie No.1",
        movie: "Coolie No.1",
        path: "https://od.lk/s/NDRfMjkzMzM4NzFf/Coolie%20No.1.mp3",
      
    },
    { Id: 10,
      name: "Gareebo Ki suno",
      movie: "Dus Lakh",
      path: "https://od.lk/s/f35729a84f5a5bdcf12d9e31b8a244222da0e20a2d2bc631962527a3bae23f65/Garibo%20Ki%20Suno.mp3",
    
  }, { Id: 11,
    name: "Tu Bin Bataye",
    movie: "Rang De Basanti",
    path: "https://od.lk/s/NDRfMjkzMzM0MzVf/Tu%20Bin%20Bataye%20-%20%28amlijatt.in%29.mp3",
  
},
  ];